### ISSUE TITLE
Enable gzip and brotli with one command

### ISSUE THREAD

**Issue by ptamarit** [gios/gzipper#49]
Hello,

Pre-compressing assets with gzip *and* with brotli is a common requirement (as long as one wants to serve optimized assets to IE11).

Right now, I have the following setup to achieve this (using `npm-run-all` instead of `&&` so that it also works on Windows):

```
  "scripts": {
    "build": "ng build",
    "compress:gzip": "gzipper --verbose dist",
    "compress:brotli": "gzipper --brotli --verbose dist",
    "postbuild": "npm-run-all --parallel compress:*"
  },
```

However, if `gzipper` could do this with in one CLI call (e.g. with something like a `--gzip` flag in order to be able to enable gzip *and* brotli), I could get rid of `npm-run-all` and make the scripts much simpler:

```
  "scripts": {
    "build": "ng build",
    "postbuild": "gzipper --gzip --brotli --verbose dist"
  },
```

Does it make sense?
Not sure how easy it would be to implement, as the code is currently only returning one instance of a compressor...

Great lib by the way, thanks a lot!
Pablo

**Comment by gios** [comment]
Hi @ptamarit , I would recommend another solution and don't mix up a lot of algorithms into one CLI command, because we have to add additional properties per each compression algorithm like instead of `--level` I should use `--gzip-level` and `--brotli-level`, etc. You could try to create a simple .js file with the following content since `compress` method returns a Promise we can combine multiple instances using `Promise.all`.

```javascript
const { Gzipper } = require("gzipper");

const gzip = new Gzipper("./test");
const brotli = new Gzipper("./test", null, {
  brotli: true
});

Promise.all([gzip.compress(), brotli.compress()])
  .then(files => console.log("success ", files))
  .catch(error => console.error(error));
```

And then just run `node ./your_file.name.js`

**Comment by ptamarit** [comment]
Hi,

The options are already geared toward specific compression algorithms (`--level` is only for gzip, `--brotli-quality` is only for brotli), but for sure the command line call would become very long and potentially confusing.

I'll go with the script option you're proposing and close the issue.
Thanks a lot for taking the time to write a working example, much appreciated!

Cheers,
Pablo
