### ISSUE TITLE
question about how gzipper can help me

### ISSUE THREAD

**Issue by andrejm7** [gios/gzipper#54]
Hello

I have a question about how gzipper can help me ..

In angular it generates the dist folder with the .zip file and the normal one. Is the angular smart enough to get the smallest file?

Otherwise my dist folder will get even bigger.

**Comment by gios** [comment]
Hi, I don't know why do you need a zip file in your dist folder but anyway gzipper will help you compress files from the dist folder (js, css, img, etc.) and reduce the size of your bundles if you correctly configured your server (use appropriate headers or modules like koa-compress or any other).

Regarding angular and smallest file, angular is only UI framework, default `ng build` command compiles and produces static files in `dist` folder and doesn't do anything with them. If you wanna reduce the downloadable size of your content from dist folder you should run something like `npx gzipper ./dist` and setup compression on your server. After that browser automatically grabs a gzipped (reduced) version of your files.

If I didn't' answer your question please provide a little bit more information about folder structure, commands you ran, etc. Currently, I close this issue because it's not related to gzipper but you feel free to continue discussing.
