### ISSUE TITLE
Running gzipper on .dist/ to ./zipped archives the files, but individually, not in a single archive!!

### ISSUE THREAD

**Issue by ied3vil** [gios/gzipper#72]
As the title says, the library works but archives each file individually. 
Am i doing something wrong? My NPM script is: 
`"build": "react-scripts build && gzipper compress ./build ./zipped",`

```
ls -l zipped 
total 96
-rw-r--r--  1 razvan.marian  1985064453   326 Dec  8 19:55 asset-manifest.json.gz
-rw-r--r--  1 razvan.marian  1985064453  3461 Dec  8 19:55 favicon.ico.gz
-rw-r--r--  1 razvan.marian  1985064453  1509 Dec  8 19:55 index.html.gz
-rw-r--r--  1 razvan.marian  1985064453  5332 Dec  8 19:55 logo192.png.gz
-rw-r--r--  1 razvan.marian  1985064453  9660 Dec  8 19:55 logo512.png.gz
-rw-r--r--  1 razvan.marian  1985064453   250 Dec  8 19:55 manifest.json.gz
-rw-r--r--  1 razvan.marian  1985064453   331 Dec  8 19:55 precache-manifest.01566b99c51188dfed91c26c7df6f1ca.js.gz
-rw-r--r--  1 razvan.marian  1985064453    78 Dec  8 19:55 robots.txt.gz
-rw-r--r--  1 razvan.marian  1985064453   684 Dec  8 19:55 service-worker.js.gz
drwxr-xr-x  4 razvan.marian  1985064453   128 Dec  8 19:55 static

```

**Comment by gios** [comment]
Hi @ied3vil ,

First of all, it's not an archivation library, you will not get a zip, rar, or any other type of archive as a result. Your npm script is completely right, it compresses every file inside `build` directory and copies them to `zipped`. You can use these files instead of real ones inside your static folder. This approach will give you a significantly reduced file size with configured gzip or brotli algorithm on your server.
