### ISSUE TITLE
Error: Can not access zstd! Is it installed?

### ISSUE THREAD

**Issue by dptoot** [gios/gzipper#90]
Version 6.2.0 brought zstd compression but since upgrading to the latest I am unable to proceed.

It looks like simple-zstd requires zstd as a peer-dependency.  Are we now required to install that as a peer to use gzipper?

```
Error: Can not access zstd! Is it installed?
```

This looks like the line in simple-git throwing the error
https://github.com/Stieneee/simple-zstd/blob/master/index.js#L13

Thanks for all the hard work!

**Comment by cherouvim** [comment]
This fails for me too. I use the following, and I do not want to use zstd at all:
```
gzipper compress build/ --include css,js --brotli
```

**Comment by gios** [comment]
Thx for the issue, I will add additional documentation for zstd compilation, especially how to install this on your system if you want to use it. Currently, the only way to fix the problem is just to install zstd on your system manually:
Brew: `brew install zstd` (zstd only)
      `brew install zlib` (whole library)
APT: `sudo apt install zstd`

**Comment by dptoot** [comment]
@gios awesome!  thanks for the quick response!

**Comment by gios** [comment]
v6.2.1 with fixed has been uploaded. I've tested it on WSL and Windows, runs fine.
